# Generated by Django 2.2.8 on 2019-12-02 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000000000000)),
                ('subtext', models.CharField(max_length=1000000000000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=1000000000000)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantum.Screen')),
            ],
        ),
    ]
